### ISSUE TITLE
Combined upper and lower bound not supported

### ISSUE THREAD

**Issue by jesseschalken** [hhvm/definition-finder#1]
I noticed a generic has only a [possible constraint and constraint relationship](https://github.com/hhvm/definition-finder/blob/4210880ff3efef22c01cd7054e97dc5067ee784e/src/definitions/ScannedGeneric.php#L19) (`super` or `as`), but generics can have both `super` and `as` at the same time (both an upper and lower bound). Example:

```php
abstract class Path {
  // ..
  public final function relativeTo<T super this as Path>(T $base): T {
    // ..
  }
  // ..
}
```

Here, `T` must be some `Path` that `this` is compatible with. definition-finder will only pick up the `as Path` part, the lower bound is lost.

**Comment by fredemmott** [comment]
cc @doublecompile
